[repo] update cogs to support dpy2 (#168)
* update aki to dpy2

* Style Reformatting

* update altdentifier to dpy2

* update linkquoter to dp2

* use aware datetimes

* Style Reformatting

* update antihonde to dpy2

* update baron datetimes, assets

* update baron menus to use views

* Style Reformatting

* [customping] use aware utc datetime

* [forcemention] remove unneccesary sleep

* Style Reformatting

* [pfpimgen] update asset saving to dpy2 syntax

* [permissionslocker] remove unnecessary async function

* [perimissionslocker] fix nameerror

* [connect4] convert to views

* Style Reformatting

* [connect4] remove print statements

* [disboardreminder] use naive datetimes

* [connect4 + pfpimgen] use display_avatar

* [plague] fix avatar asset calls

* Style Reformatting

* [simplecalculator] fix title limit error

* Style Reformatting

* [webhook] avatar asset calls

* [embedutils] fix asset calls

* Style Reformatting

* [aki] make interaction check ephemeral

* [embedutils] some refactoring

* [linkquoter] use lazy logging formatting

* [disboardreminder] refactor listener logic

* [tags] refactor mixins

* [tags] cleanup pre-commit breakage

* [tags] update menus to views

* Style Reformatting

* [tags] tag override typo

* [utils] make specify encodings for files

* update readme

* Update commands.py

* [tags] update version

* [slashtags] initial dpy2 conversions

* [slashtags] update install message

* [slashtags] change interaction parse order

* [embedutils] add support for sending lists through json, yaml, pastbin, and post subcommands

* [tags] fix search guild icon

* [slashtags] begin wrapping dpy2 interactions

* [slashtags] base model works on dpy2

* [slashtags] complete dpy2 processing

* [slashtags] major version bump, remove some no longer needed things

* [slashtags] use views for slashtag creation, y/n prompts, and menus

* [tags] fix guild icon in info command

* [slashtags] add InteractionWrapper.created_at

* [pre-commit] add newline between local hooks

* [slashtags] add global info command

* [slashtags] fix guild.icon in SlashTag.send_info

* [slashtags] add PartialMessageable support to FakeMessage

* the previous commit, but working

* [slashtags] add InteractionWrapper.get_channel to return proper dm channels

* [slashtags] missing await

* [slashtags] fix typo in InteractionWrapper.get_channel

* [linkquoter] fix thread bugs

* [slashtags] option picker timeout bugfix

* [slashtags] prevent replis from pinging

* [repo] dpy2 asynchronous cog loading changes (#129)

* dpy2 async changes on extension load

* dpy2 async changes

* dpy2 async changes

* dpy2 async changes

* awaited dpy2 async changes

* fix

* made changes as requested

* checking something

* order of parameters changed

* order of parameters changed

* probable fix

* changed generator experssion to list comprehension

* this should fix it :/

* it's `Asset.replace()` now

* made changes as per requested

* restored to original as requested

* order of parameters changed

* [baron] fix Button._callback args order

* [baron] revert ConfirmationView.disable_all parameter order

* fix some other changes

Co-authored-by: PhenoM4n4n <61065078+phenom4n4n@users.noreply.github.com>

* Style Reformatting

* [Baron] fix `build_cache` missing. (#145)

* [Baron] fix `build_cache` mistakenly getting mixed with `cog_load`.

* ensure cache is built on cog load

Co-authored-by: PhenoM4n4n <61065078+phenom4n4n@users.noreply.github.com>

* Update aki.py (#149)

async with typing, ctx has no 'trigger_typing' attribute

* [baron] trigger_typing() -> typing() (#154)

it should be typing() for dpy2

* Style Reformatting

* [baron] handle guilds without an icon

AttributeError: 'NoneType' object has no attribute 'url'

* Resolves the error caused by red#5843 (#161)

* resolve errors

* bump version

* [banchart] Handle .bans breakage (#164)

* [dpy2] fix `Context.trigger_typing()` not being an attribute anymore on dpy v2.1.0 (#152)

* [BanChart] fix `ctx.trigger_typing`

* [Baron] Fix `ctx.trigger_typing()`

* [Lock] Fix `ctx.trigger_typing()`

* [PfpImgen] Fix `ctx.trigger_typing()`

* [Tags] FIx `ctx.trigger_typing()`

* [Baron] shift `ctx.send` outside `ctx.typing`

* [Lock] remove try excepts

* [Lock] shift `ctx.send` outside `ctx.typing`

* [PfpImgen] fix duplicate]

* [Baron] shift back to `await ctx.typing()`

* [Lock] shift to `await ctx.typing()`

* [Lock] shift to `await ctx.typing()`

* style reformatting (Black)

---------

Co-authored-by: PhenoM4n4n <61065078+phenom4n4n@users.noreply.github.com>

* Style Reformatting

* merge changes from master

* [tags] update tse version

* [aki] change typing behavior

---------

Co-authored-by: {{ github.actor }} <phenom4n4n@users.noreply.github.com>
Co-authored-by: Lemon Rose <78662983+japandotorg@users.noreply.github.com>
Co-authored-by: Alex <58824393+vertyco@users.noreply.github.com>
Co-authored-by: kpop dev <28566705+kpopdev@users.noreply.github.com>
Co-authored-by: sravan <miniclip1956@gmail.com>
Co-authored-by: Flame442 <34169552+Flame442@users.noreply.github.com>